allow-breeding: true
allow-ditto-ditto-breeding: false
allow-ranch-expansion: true
allow-random-breeding-eggs-to-be-legendary: false
breeding-ticks: 4500
max-cumulative-pokemon-in-ranch: 0
num-breeding-levels: 5
oval-charm-multiplier: 0.5
steps-per-egg-cycle: 255
use-breeding-environment: false
allow-random-breeding-eggs-to-be-ultrabeast: false
allow-random-breeding-eggs-to-be-mythic: false
default-day-care-amount: 3
